import { BootstrapSalesChannelsNavigationData, BootstrapSalesChannelsNavigationVariables, BootstrapNavigationCatalogData, BootstrapNavigationCatalogVariables, CreateCategoryData, CreateCategoryVariables, UpdateCategoryData, UpdateCategoryVariables, ArchiveCategoryData, ArchiveCategoryVariables, CreateSubcategoryData, CreateSubcategoryVariables, UpdateSubcategoryData, UpdateSubcategoryVariables, ArchiveSubcategoryData, ArchiveSubcategoryVariables, RestoreCategoryData, RestoreCategoryVariables, RestoreSubcategoryData, RestoreSubcategoryVariables, CreateCategoriesBatchData, CreateCategoriesBatchVariables, CreateSubcategoriesBatchData, CreateSubcategoriesBatchVariables, SaveBranchData, SaveBranchVariables, SetBranchStatusData, SetBranchStatusVariables, SaveSupplierData, SaveSupplierVariables, SetSupplierStatusData, SetSupplierStatusVariables, SaveCustomerData, SaveCustomerVariables, SetCustomerStatusData, SetCustomerStatusVariables, SaveProductData, SaveProductVariables, SetProductStatusData, SetProductStatusVariables, SaveProductComponentsData, SaveProductComponentsVariables, SavePromotionData, SavePromotionVariables, SetPromotionStatusData, SetPromotionStatusVariables, SetCategoriesStatusBatchData, SetCategoriesStatusBatchVariables, SetSubcategoriesStatusBatchData, SetSubcategoriesStatusBatchVariables, SetBranchesStatusBatchData, SetBranchesStatusBatchVariables, SetSuppliersStatusBatchData, SetSuppliersStatusBatchVariables, SetCustomersStatusBatchData, SetCustomersStatusBatchVariables, SetProductsStatusBatchData, SetProductsStatusBatchVariables, EnsureSalesDefaultsData, PostSaleData, PostSaleVariables, CancelSaleData, CancelSaleVariables, CreatePlatformTenantData, CreatePlatformTenantVariables, SetPlatformTenantStatusData, SetPlatformTenantStatusVariables, LinkPlatformUserData, LinkPlatformUserVariables, SetPlatformUserStatusData, SetPlatformUserStatusVariables, SetPlatformRolePermissionData, SetPlatformRolePermissionVariables, PostStockAdjustmentData, PostStockAdjustmentVariables, PostStockTransferData, PostStockTransferVariables, SaveStockBatchData, SaveStockBatchVariables, ReverseStockOperationData, ReverseStockOperationVariables, OpenCashSessionData, OpenCashSessionVariables, RegisterCashMovementData, RegisterCashMovementVariables, ClaimDeviceSessionData, ClaimDeviceSessionVariables, TouchDeviceSessionData, TouchDeviceSessionVariables, ReleaseDeviceSessionData, ReleaseDeviceSessionVariables, CreateSalesChannelConnectionData, CreateSalesChannelConnectionVariables, UpdateSalesChannelConnectionData, UpdateSalesChannelConnectionVariables, ArchiveSalesChannelConnectionData, ArchiveSalesChannelConnectionVariables, CloseCashSessionData, CloseCashSessionVariables, GetCurrentUserData, GetCurrentUserAccessData, ValidateDeviceSessionData, ValidateDeviceSessionVariables, SalesChannelWorkspaceData, SalesChannelWorkspaceVariables, SalesWorkspaceData, SalesWorkspaceVariables, ListSalesData, ListSalesVariables, SaleDetailsData, SaleDetailsVariables, ListCategoriesData, ListCategoriesVariables, ListSubcategoriesData, ListSubcategoriesVariables, CategoryOptionsData, CategoryOptionsVariables, ListBranchesData, ListBranchesVariables, ListSuppliersData, ListSuppliersVariables, ListCustomersData, ListCustomersVariables, ListProductsData, ListProductsVariables, RegistrationOptionsData, RegistrationOptionsVariables, ProductComponentsData, ProductComponentsVariables, ProductPromotionsData, ProductPromotionsVariables, PlatformAdminWorkspaceData, PlatformAdminWorkspaceVariables, StockWorkspaceData, StockWorkspaceVariables, DailyProfitDashboardData, DailyProfitDashboardVariables, StockOperationDetailsData, StockOperationDetailsVariables, FinancialIndicatorsDashboardData, FinancialIndicatorsDashboardVariables, OperationalAnalyticsDashboardData, OperationalAnalyticsDashboardVariables, RecoverPlatformAdministratorData } from '../';
import { UseDataConnectQueryResult, useDataConnectQueryOptions, UseDataConnectMutationResult, useDataConnectMutationOptions} from '@tanstack-query-firebase/react/data-connect';
import { UseQueryResult, UseMutationResult} from '@tanstack/react-query';
import { DataConnect } from 'firebase/data-connect';
import { FirebaseError } from 'firebase/app';


export function useBootstrapSalesChannelsNavigation(options?: useDataConnectMutationOptions<BootstrapSalesChannelsNavigationData, FirebaseError, BootstrapSalesChannelsNavigationVariables>): UseDataConnectMutationResult<BootstrapSalesChannelsNavigationData, BootstrapSalesChannelsNavigationVariables>;
export function useBootstrapSalesChannelsNavigation(dc: DataConnect, options?: useDataConnectMutationOptions<BootstrapSalesChannelsNavigationData, FirebaseError, BootstrapSalesChannelsNavigationVariables>): UseDataConnectMutationResult<BootstrapSalesChannelsNavigationData, BootstrapSalesChannelsNavigationVariables>;

export function useBootstrapNavigationCatalog(options?: useDataConnectMutationOptions<BootstrapNavigationCatalogData, FirebaseError, BootstrapNavigationCatalogVariables>): UseDataConnectMutationResult<BootstrapNavigationCatalogData, BootstrapNavigationCatalogVariables>;
export function useBootstrapNavigationCatalog(dc: DataConnect, options?: useDataConnectMutationOptions<BootstrapNavigationCatalogData, FirebaseError, BootstrapNavigationCatalogVariables>): UseDataConnectMutationResult<BootstrapNavigationCatalogData, BootstrapNavigationCatalogVariables>;

export function useCreateCategory(options?: useDataConnectMutationOptions<CreateCategoryData, FirebaseError, CreateCategoryVariables>): UseDataConnectMutationResult<CreateCategoryData, CreateCategoryVariables>;
export function useCreateCategory(dc: DataConnect, options?: useDataConnectMutationOptions<CreateCategoryData, FirebaseError, CreateCategoryVariables>): UseDataConnectMutationResult<CreateCategoryData, CreateCategoryVariables>;

export function useUpdateCategory(options?: useDataConnectMutationOptions<UpdateCategoryData, FirebaseError, UpdateCategoryVariables>): UseDataConnectMutationResult<UpdateCategoryData, UpdateCategoryVariables>;
export function useUpdateCategory(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateCategoryData, FirebaseError, UpdateCategoryVariables>): UseDataConnectMutationResult<UpdateCategoryData, UpdateCategoryVariables>;

export function useArchiveCategory(options?: useDataConnectMutationOptions<ArchiveCategoryData, FirebaseError, ArchiveCategoryVariables>): UseDataConnectMutationResult<ArchiveCategoryData, ArchiveCategoryVariables>;
export function useArchiveCategory(dc: DataConnect, options?: useDataConnectMutationOptions<ArchiveCategoryData, FirebaseError, ArchiveCategoryVariables>): UseDataConnectMutationResult<ArchiveCategoryData, ArchiveCategoryVariables>;

export function useCreateSubcategory(options?: useDataConnectMutationOptions<CreateSubcategoryData, FirebaseError, CreateSubcategoryVariables>): UseDataConnectMutationResult<CreateSubcategoryData, CreateSubcategoryVariables>;
export function useCreateSubcategory(dc: DataConnect, options?: useDataConnectMutationOptions<CreateSubcategoryData, FirebaseError, CreateSubcategoryVariables>): UseDataConnectMutationResult<CreateSubcategoryData, CreateSubcategoryVariables>;

export function useUpdateSubcategory(options?: useDataConnectMutationOptions<UpdateSubcategoryData, FirebaseError, UpdateSubcategoryVariables>): UseDataConnectMutationResult<UpdateSubcategoryData, UpdateSubcategoryVariables>;
export function useUpdateSubcategory(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateSubcategoryData, FirebaseError, UpdateSubcategoryVariables>): UseDataConnectMutationResult<UpdateSubcategoryData, UpdateSubcategoryVariables>;

export function useArchiveSubcategory(options?: useDataConnectMutationOptions<ArchiveSubcategoryData, FirebaseError, ArchiveSubcategoryVariables>): UseDataConnectMutationResult<ArchiveSubcategoryData, ArchiveSubcategoryVariables>;
export function useArchiveSubcategory(dc: DataConnect, options?: useDataConnectMutationOptions<ArchiveSubcategoryData, FirebaseError, ArchiveSubcategoryVariables>): UseDataConnectMutationResult<ArchiveSubcategoryData, ArchiveSubcategoryVariables>;

export function useRestoreCategory(options?: useDataConnectMutationOptions<RestoreCategoryData, FirebaseError, RestoreCategoryVariables>): UseDataConnectMutationResult<RestoreCategoryData, RestoreCategoryVariables>;
export function useRestoreCategory(dc: DataConnect, options?: useDataConnectMutationOptions<RestoreCategoryData, FirebaseError, RestoreCategoryVariables>): UseDataConnectMutationResult<RestoreCategoryData, RestoreCategoryVariables>;

export function useRestoreSubcategory(options?: useDataConnectMutationOptions<RestoreSubcategoryData, FirebaseError, RestoreSubcategoryVariables>): UseDataConnectMutationResult<RestoreSubcategoryData, RestoreSubcategoryVariables>;
export function useRestoreSubcategory(dc: DataConnect, options?: useDataConnectMutationOptions<RestoreSubcategoryData, FirebaseError, RestoreSubcategoryVariables>): UseDataConnectMutationResult<RestoreSubcategoryData, RestoreSubcategoryVariables>;

export function useCreateCategoriesBatch(options?: useDataConnectMutationOptions<CreateCategoriesBatchData, FirebaseError, CreateCategoriesBatchVariables>): UseDataConnectMutationResult<CreateCategoriesBatchData, CreateCategoriesBatchVariables>;
export function useCreateCategoriesBatch(dc: DataConnect, options?: useDataConnectMutationOptions<CreateCategoriesBatchData, FirebaseError, CreateCategoriesBatchVariables>): UseDataConnectMutationResult<CreateCategoriesBatchData, CreateCategoriesBatchVariables>;

export function useCreateSubcategoriesBatch(options?: useDataConnectMutationOptions<CreateSubcategoriesBatchData, FirebaseError, CreateSubcategoriesBatchVariables>): UseDataConnectMutationResult<CreateSubcategoriesBatchData, CreateSubcategoriesBatchVariables>;
export function useCreateSubcategoriesBatch(dc: DataConnect, options?: useDataConnectMutationOptions<CreateSubcategoriesBatchData, FirebaseError, CreateSubcategoriesBatchVariables>): UseDataConnectMutationResult<CreateSubcategoriesBatchData, CreateSubcategoriesBatchVariables>;

export function useSaveBranch(options?: useDataConnectMutationOptions<SaveBranchData, FirebaseError, SaveBranchVariables>): UseDataConnectMutationResult<SaveBranchData, SaveBranchVariables>;
export function useSaveBranch(dc: DataConnect, options?: useDataConnectMutationOptions<SaveBranchData, FirebaseError, SaveBranchVariables>): UseDataConnectMutationResult<SaveBranchData, SaveBranchVariables>;

export function useSetBranchStatus(options?: useDataConnectMutationOptions<SetBranchStatusData, FirebaseError, SetBranchStatusVariables>): UseDataConnectMutationResult<SetBranchStatusData, SetBranchStatusVariables>;
export function useSetBranchStatus(dc: DataConnect, options?: useDataConnectMutationOptions<SetBranchStatusData, FirebaseError, SetBranchStatusVariables>): UseDataConnectMutationResult<SetBranchStatusData, SetBranchStatusVariables>;

export function useSaveSupplier(options?: useDataConnectMutationOptions<SaveSupplierData, FirebaseError, SaveSupplierVariables>): UseDataConnectMutationResult<SaveSupplierData, SaveSupplierVariables>;
export function useSaveSupplier(dc: DataConnect, options?: useDataConnectMutationOptions<SaveSupplierData, FirebaseError, SaveSupplierVariables>): UseDataConnectMutationResult<SaveSupplierData, SaveSupplierVariables>;

export function useSetSupplierStatus(options?: useDataConnectMutationOptions<SetSupplierStatusData, FirebaseError, SetSupplierStatusVariables>): UseDataConnectMutationResult<SetSupplierStatusData, SetSupplierStatusVariables>;
export function useSetSupplierStatus(dc: DataConnect, options?: useDataConnectMutationOptions<SetSupplierStatusData, FirebaseError, SetSupplierStatusVariables>): UseDataConnectMutationResult<SetSupplierStatusData, SetSupplierStatusVariables>;

export function useSaveCustomer(options?: useDataConnectMutationOptions<SaveCustomerData, FirebaseError, SaveCustomerVariables>): UseDataConnectMutationResult<SaveCustomerData, SaveCustomerVariables>;
export function useSaveCustomer(dc: DataConnect, options?: useDataConnectMutationOptions<SaveCustomerData, FirebaseError, SaveCustomerVariables>): UseDataConnectMutationResult<SaveCustomerData, SaveCustomerVariables>;

export function useSetCustomerStatus(options?: useDataConnectMutationOptions<SetCustomerStatusData, FirebaseError, SetCustomerStatusVariables>): UseDataConnectMutationResult<SetCustomerStatusData, SetCustomerStatusVariables>;
export function useSetCustomerStatus(dc: DataConnect, options?: useDataConnectMutationOptions<SetCustomerStatusData, FirebaseError, SetCustomerStatusVariables>): UseDataConnectMutationResult<SetCustomerStatusData, SetCustomerStatusVariables>;

export function useSaveProduct(options?: useDataConnectMutationOptions<SaveProductData, FirebaseError, SaveProductVariables>): UseDataConnectMutationResult<SaveProductData, SaveProductVariables>;
export function useSaveProduct(dc: DataConnect, options?: useDataConnectMutationOptions<SaveProductData, FirebaseError, SaveProductVariables>): UseDataConnectMutationResult<SaveProductData, SaveProductVariables>;

export function useSetProductStatus(options?: useDataConnectMutationOptions<SetProductStatusData, FirebaseError, SetProductStatusVariables>): UseDataConnectMutationResult<SetProductStatusData, SetProductStatusVariables>;
export function useSetProductStatus(dc: DataConnect, options?: useDataConnectMutationOptions<SetProductStatusData, FirebaseError, SetProductStatusVariables>): UseDataConnectMutationResult<SetProductStatusData, SetProductStatusVariables>;

export function useSaveProductComponents(options?: useDataConnectMutationOptions<SaveProductComponentsData, FirebaseError, SaveProductComponentsVariables>): UseDataConnectMutationResult<SaveProductComponentsData, SaveProductComponentsVariables>;
export function useSaveProductComponents(dc: DataConnect, options?: useDataConnectMutationOptions<SaveProductComponentsData, FirebaseError, SaveProductComponentsVariables>): UseDataConnectMutationResult<SaveProductComponentsData, SaveProductComponentsVariables>;

export function useSavePromotion(options?: useDataConnectMutationOptions<SavePromotionData, FirebaseError, SavePromotionVariables>): UseDataConnectMutationResult<SavePromotionData, SavePromotionVariables>;
export function useSavePromotion(dc: DataConnect, options?: useDataConnectMutationOptions<SavePromotionData, FirebaseError, SavePromotionVariables>): UseDataConnectMutationResult<SavePromotionData, SavePromotionVariables>;

export function useSetPromotionStatus(options?: useDataConnectMutationOptions<SetPromotionStatusData, FirebaseError, SetPromotionStatusVariables>): UseDataConnectMutationResult<SetPromotionStatusData, SetPromotionStatusVariables>;
export function useSetPromotionStatus(dc: DataConnect, options?: useDataConnectMutationOptions<SetPromotionStatusData, FirebaseError, SetPromotionStatusVariables>): UseDataConnectMutationResult<SetPromotionStatusData, SetPromotionStatusVariables>;

export function useSetCategoriesStatusBatch(options?: useDataConnectMutationOptions<SetCategoriesStatusBatchData, FirebaseError, SetCategoriesStatusBatchVariables>): UseDataConnectMutationResult<SetCategoriesStatusBatchData, SetCategoriesStatusBatchVariables>;
export function useSetCategoriesStatusBatch(dc: DataConnect, options?: useDataConnectMutationOptions<SetCategoriesStatusBatchData, FirebaseError, SetCategoriesStatusBatchVariables>): UseDataConnectMutationResult<SetCategoriesStatusBatchData, SetCategoriesStatusBatchVariables>;

export function useSetSubcategoriesStatusBatch(options?: useDataConnectMutationOptions<SetSubcategoriesStatusBatchData, FirebaseError, SetSubcategoriesStatusBatchVariables>): UseDataConnectMutationResult<SetSubcategoriesStatusBatchData, SetSubcategoriesStatusBatchVariables>;
export function useSetSubcategoriesStatusBatch(dc: DataConnect, options?: useDataConnectMutationOptions<SetSubcategoriesStatusBatchData, FirebaseError, SetSubcategoriesStatusBatchVariables>): UseDataConnectMutationResult<SetSubcategoriesStatusBatchData, SetSubcategoriesStatusBatchVariables>;

export function useSetBranchesStatusBatch(options?: useDataConnectMutationOptions<SetBranchesStatusBatchData, FirebaseError, SetBranchesStatusBatchVariables>): UseDataConnectMutationResult<SetBranchesStatusBatchData, SetBranchesStatusBatchVariables>;
export function useSetBranchesStatusBatch(dc: DataConnect, options?: useDataConnectMutationOptions<SetBranchesStatusBatchData, FirebaseError, SetBranchesStatusBatchVariables>): UseDataConnectMutationResult<SetBranchesStatusBatchData, SetBranchesStatusBatchVariables>;

export function useSetSuppliersStatusBatch(options?: useDataConnectMutationOptions<SetSuppliersStatusBatchData, FirebaseError, SetSuppliersStatusBatchVariables>): UseDataConnectMutationResult<SetSuppliersStatusBatchData, SetSuppliersStatusBatchVariables>;
export function useSetSuppliersStatusBatch(dc: DataConnect, options?: useDataConnectMutationOptions<SetSuppliersStatusBatchData, FirebaseError, SetSuppliersStatusBatchVariables>): UseDataConnectMutationResult<SetSuppliersStatusBatchData, SetSuppliersStatusBatchVariables>;

export function useSetCustomersStatusBatch(options?: useDataConnectMutationOptions<SetCustomersStatusBatchData, FirebaseError, SetCustomersStatusBatchVariables>): UseDataConnectMutationResult<SetCustomersStatusBatchData, SetCustomersStatusBatchVariables>;
export function useSetCustomersStatusBatch(dc: DataConnect, options?: useDataConnectMutationOptions<SetCustomersStatusBatchData, FirebaseError, SetCustomersStatusBatchVariables>): UseDataConnectMutationResult<SetCustomersStatusBatchData, SetCustomersStatusBatchVariables>;

export function useSetProductsStatusBatch(options?: useDataConnectMutationOptions<SetProductsStatusBatchData, FirebaseError, SetProductsStatusBatchVariables>): UseDataConnectMutationResult<SetProductsStatusBatchData, SetProductsStatusBatchVariables>;
export function useSetProductsStatusBatch(dc: DataConnect, options?: useDataConnectMutationOptions<SetProductsStatusBatchData, FirebaseError, SetProductsStatusBatchVariables>): UseDataConnectMutationResult<SetProductsStatusBatchData, SetProductsStatusBatchVariables>;

export function useEnsureSalesDefaults(options?: useDataConnectMutationOptions<EnsureSalesDefaultsData, FirebaseError, void>): UseDataConnectMutationResult<EnsureSalesDefaultsData, undefined>;
export function useEnsureSalesDefaults(dc: DataConnect, options?: useDataConnectMutationOptions<EnsureSalesDefaultsData, FirebaseError, void>): UseDataConnectMutationResult<EnsureSalesDefaultsData, undefined>;

export function usePostSale(options?: useDataConnectMutationOptions<PostSaleData, FirebaseError, PostSaleVariables>): UseDataConnectMutationResult<PostSaleData, PostSaleVariables>;
export function usePostSale(dc: DataConnect, options?: useDataConnectMutationOptions<PostSaleData, FirebaseError, PostSaleVariables>): UseDataConnectMutationResult<PostSaleData, PostSaleVariables>;

export function useCancelSale(options?: useDataConnectMutationOptions<CancelSaleData, FirebaseError, CancelSaleVariables>): UseDataConnectMutationResult<CancelSaleData, CancelSaleVariables>;
export function useCancelSale(dc: DataConnect, options?: useDataConnectMutationOptions<CancelSaleData, FirebaseError, CancelSaleVariables>): UseDataConnectMutationResult<CancelSaleData, CancelSaleVariables>;

export function useCreatePlatformTenant(options?: useDataConnectMutationOptions<CreatePlatformTenantData, FirebaseError, CreatePlatformTenantVariables>): UseDataConnectMutationResult<CreatePlatformTenantData, CreatePlatformTenantVariables>;
export function useCreatePlatformTenant(dc: DataConnect, options?: useDataConnectMutationOptions<CreatePlatformTenantData, FirebaseError, CreatePlatformTenantVariables>): UseDataConnectMutationResult<CreatePlatformTenantData, CreatePlatformTenantVariables>;

export function useSetPlatformTenantStatus(options?: useDataConnectMutationOptions<SetPlatformTenantStatusData, FirebaseError, SetPlatformTenantStatusVariables>): UseDataConnectMutationResult<SetPlatformTenantStatusData, SetPlatformTenantStatusVariables>;
export function useSetPlatformTenantStatus(dc: DataConnect, options?: useDataConnectMutationOptions<SetPlatformTenantStatusData, FirebaseError, SetPlatformTenantStatusVariables>): UseDataConnectMutationResult<SetPlatformTenantStatusData, SetPlatformTenantStatusVariables>;

export function useLinkPlatformUser(options?: useDataConnectMutationOptions<LinkPlatformUserData, FirebaseError, LinkPlatformUserVariables>): UseDataConnectMutationResult<LinkPlatformUserData, LinkPlatformUserVariables>;
export function useLinkPlatformUser(dc: DataConnect, options?: useDataConnectMutationOptions<LinkPlatformUserData, FirebaseError, LinkPlatformUserVariables>): UseDataConnectMutationResult<LinkPlatformUserData, LinkPlatformUserVariables>;

export function useSetPlatformUserStatus(options?: useDataConnectMutationOptions<SetPlatformUserStatusData, FirebaseError, SetPlatformUserStatusVariables>): UseDataConnectMutationResult<SetPlatformUserStatusData, SetPlatformUserStatusVariables>;
export function useSetPlatformUserStatus(dc: DataConnect, options?: useDataConnectMutationOptions<SetPlatformUserStatusData, FirebaseError, SetPlatformUserStatusVariables>): UseDataConnectMutationResult<SetPlatformUserStatusData, SetPlatformUserStatusVariables>;

export function useSetPlatformRolePermission(options?: useDataConnectMutationOptions<SetPlatformRolePermissionData, FirebaseError, SetPlatformRolePermissionVariables>): UseDataConnectMutationResult<SetPlatformRolePermissionData, SetPlatformRolePermissionVariables>;
export function useSetPlatformRolePermission(dc: DataConnect, options?: useDataConnectMutationOptions<SetPlatformRolePermissionData, FirebaseError, SetPlatformRolePermissionVariables>): UseDataConnectMutationResult<SetPlatformRolePermissionData, SetPlatformRolePermissionVariables>;

export function usePostStockAdjustment(options?: useDataConnectMutationOptions<PostStockAdjustmentData, FirebaseError, PostStockAdjustmentVariables>): UseDataConnectMutationResult<PostStockAdjustmentData, PostStockAdjustmentVariables>;
export function usePostStockAdjustment(dc: DataConnect, options?: useDataConnectMutationOptions<PostStockAdjustmentData, FirebaseError, PostStockAdjustmentVariables>): UseDataConnectMutationResult<PostStockAdjustmentData, PostStockAdjustmentVariables>;

export function usePostStockTransfer(options?: useDataConnectMutationOptions<PostStockTransferData, FirebaseError, PostStockTransferVariables>): UseDataConnectMutationResult<PostStockTransferData, PostStockTransferVariables>;
export function usePostStockTransfer(dc: DataConnect, options?: useDataConnectMutationOptions<PostStockTransferData, FirebaseError, PostStockTransferVariables>): UseDataConnectMutationResult<PostStockTransferData, PostStockTransferVariables>;

export function useSaveStockBatch(options?: useDataConnectMutationOptions<SaveStockBatchData, FirebaseError, SaveStockBatchVariables>): UseDataConnectMutationResult<SaveStockBatchData, SaveStockBatchVariables>;
export function useSaveStockBatch(dc: DataConnect, options?: useDataConnectMutationOptions<SaveStockBatchData, FirebaseError, SaveStockBatchVariables>): UseDataConnectMutationResult<SaveStockBatchData, SaveStockBatchVariables>;

export function useReverseStockOperation(options?: useDataConnectMutationOptions<ReverseStockOperationData, FirebaseError, ReverseStockOperationVariables>): UseDataConnectMutationResult<ReverseStockOperationData, ReverseStockOperationVariables>;
export function useReverseStockOperation(dc: DataConnect, options?: useDataConnectMutationOptions<ReverseStockOperationData, FirebaseError, ReverseStockOperationVariables>): UseDataConnectMutationResult<ReverseStockOperationData, ReverseStockOperationVariables>;

export function useOpenCashSession(options?: useDataConnectMutationOptions<OpenCashSessionData, FirebaseError, OpenCashSessionVariables>): UseDataConnectMutationResult<OpenCashSessionData, OpenCashSessionVariables>;
export function useOpenCashSession(dc: DataConnect, options?: useDataConnectMutationOptions<OpenCashSessionData, FirebaseError, OpenCashSessionVariables>): UseDataConnectMutationResult<OpenCashSessionData, OpenCashSessionVariables>;

export function useRegisterCashMovement(options?: useDataConnectMutationOptions<RegisterCashMovementData, FirebaseError, RegisterCashMovementVariables>): UseDataConnectMutationResult<RegisterCashMovementData, RegisterCashMovementVariables>;
export function useRegisterCashMovement(dc: DataConnect, options?: useDataConnectMutationOptions<RegisterCashMovementData, FirebaseError, RegisterCashMovementVariables>): UseDataConnectMutationResult<RegisterCashMovementData, RegisterCashMovementVariables>;

export function useClaimDeviceSession(options?: useDataConnectMutationOptions<ClaimDeviceSessionData, FirebaseError, ClaimDeviceSessionVariables>): UseDataConnectMutationResult<ClaimDeviceSessionData, ClaimDeviceSessionVariables>;
export function useClaimDeviceSession(dc: DataConnect, options?: useDataConnectMutationOptions<ClaimDeviceSessionData, FirebaseError, ClaimDeviceSessionVariables>): UseDataConnectMutationResult<ClaimDeviceSessionData, ClaimDeviceSessionVariables>;

export function useTouchDeviceSession(options?: useDataConnectMutationOptions<TouchDeviceSessionData, FirebaseError, TouchDeviceSessionVariables>): UseDataConnectMutationResult<TouchDeviceSessionData, TouchDeviceSessionVariables>;
export function useTouchDeviceSession(dc: DataConnect, options?: useDataConnectMutationOptions<TouchDeviceSessionData, FirebaseError, TouchDeviceSessionVariables>): UseDataConnectMutationResult<TouchDeviceSessionData, TouchDeviceSessionVariables>;

export function useReleaseDeviceSession(options?: useDataConnectMutationOptions<ReleaseDeviceSessionData, FirebaseError, ReleaseDeviceSessionVariables>): UseDataConnectMutationResult<ReleaseDeviceSessionData, ReleaseDeviceSessionVariables>;
export function useReleaseDeviceSession(dc: DataConnect, options?: useDataConnectMutationOptions<ReleaseDeviceSessionData, FirebaseError, ReleaseDeviceSessionVariables>): UseDataConnectMutationResult<ReleaseDeviceSessionData, ReleaseDeviceSessionVariables>;

export function useCreateSalesChannelConnection(options?: useDataConnectMutationOptions<CreateSalesChannelConnectionData, FirebaseError, CreateSalesChannelConnectionVariables>): UseDataConnectMutationResult<CreateSalesChannelConnectionData, CreateSalesChannelConnectionVariables>;
export function useCreateSalesChannelConnection(dc: DataConnect, options?: useDataConnectMutationOptions<CreateSalesChannelConnectionData, FirebaseError, CreateSalesChannelConnectionVariables>): UseDataConnectMutationResult<CreateSalesChannelConnectionData, CreateSalesChannelConnectionVariables>;

export function useUpdateSalesChannelConnection(options?: useDataConnectMutationOptions<UpdateSalesChannelConnectionData, FirebaseError, UpdateSalesChannelConnectionVariables>): UseDataConnectMutationResult<UpdateSalesChannelConnectionData, UpdateSalesChannelConnectionVariables>;
export function useUpdateSalesChannelConnection(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateSalesChannelConnectionData, FirebaseError, UpdateSalesChannelConnectionVariables>): UseDataConnectMutationResult<UpdateSalesChannelConnectionData, UpdateSalesChannelConnectionVariables>;

export function useArchiveSalesChannelConnection(options?: useDataConnectMutationOptions<ArchiveSalesChannelConnectionData, FirebaseError, ArchiveSalesChannelConnectionVariables>): UseDataConnectMutationResult<ArchiveSalesChannelConnectionData, ArchiveSalesChannelConnectionVariables>;
export function useArchiveSalesChannelConnection(dc: DataConnect, options?: useDataConnectMutationOptions<ArchiveSalesChannelConnectionData, FirebaseError, ArchiveSalesChannelConnectionVariables>): UseDataConnectMutationResult<ArchiveSalesChannelConnectionData, ArchiveSalesChannelConnectionVariables>;

export function useCloseCashSession(options?: useDataConnectMutationOptions<CloseCashSessionData, FirebaseError, CloseCashSessionVariables>): UseDataConnectMutationResult<CloseCashSessionData, CloseCashSessionVariables>;
export function useCloseCashSession(dc: DataConnect, options?: useDataConnectMutationOptions<CloseCashSessionData, FirebaseError, CloseCashSessionVariables>): UseDataConnectMutationResult<CloseCashSessionData, CloseCashSessionVariables>;

export function useGetCurrentUser(options?: useDataConnectQueryOptions<GetCurrentUserData>): UseDataConnectQueryResult<GetCurrentUserData, undefined>;
export function useGetCurrentUser(dc: DataConnect, options?: useDataConnectQueryOptions<GetCurrentUserData>): UseDataConnectQueryResult<GetCurrentUserData, undefined>;

export function useGetCurrentUserAccess(options?: useDataConnectQueryOptions<GetCurrentUserAccessData>): UseDataConnectQueryResult<GetCurrentUserAccessData, undefined>;
export function useGetCurrentUserAccess(dc: DataConnect, options?: useDataConnectQueryOptions<GetCurrentUserAccessData>): UseDataConnectQueryResult<GetCurrentUserAccessData, undefined>;

export function useValidateDeviceSession(vars: ValidateDeviceSessionVariables, options?: useDataConnectQueryOptions<ValidateDeviceSessionData>): UseDataConnectQueryResult<ValidateDeviceSessionData, ValidateDeviceSessionVariables>;
export function useValidateDeviceSession(dc: DataConnect, vars: ValidateDeviceSessionVariables, options?: useDataConnectQueryOptions<ValidateDeviceSessionData>): UseDataConnectQueryResult<ValidateDeviceSessionData, ValidateDeviceSessionVariables>;

export function useSalesChannelWorkspace(vars: SalesChannelWorkspaceVariables, options?: useDataConnectQueryOptions<SalesChannelWorkspaceData>): UseDataConnectQueryResult<SalesChannelWorkspaceData, SalesChannelWorkspaceVariables>;
export function useSalesChannelWorkspace(dc: DataConnect, vars: SalesChannelWorkspaceVariables, options?: useDataConnectQueryOptions<SalesChannelWorkspaceData>): UseDataConnectQueryResult<SalesChannelWorkspaceData, SalesChannelWorkspaceVariables>;

export function useSalesWorkspace(vars: SalesWorkspaceVariables, options?: useDataConnectQueryOptions<SalesWorkspaceData>): UseDataConnectQueryResult<SalesWorkspaceData, SalesWorkspaceVariables>;
export function useSalesWorkspace(dc: DataConnect, vars: SalesWorkspaceVariables, options?: useDataConnectQueryOptions<SalesWorkspaceData>): UseDataConnectQueryResult<SalesWorkspaceData, SalesWorkspaceVariables>;

export function useListSales(vars: ListSalesVariables, options?: useDataConnectQueryOptions<ListSalesData>): UseDataConnectQueryResult<ListSalesData, ListSalesVariables>;
export function useListSales(dc: DataConnect, vars: ListSalesVariables, options?: useDataConnectQueryOptions<ListSalesData>): UseDataConnectQueryResult<ListSalesData, ListSalesVariables>;

export function useSaleDetails(vars: SaleDetailsVariables, options?: useDataConnectQueryOptions<SaleDetailsData>): UseDataConnectQueryResult<SaleDetailsData, SaleDetailsVariables>;
export function useSaleDetails(dc: DataConnect, vars: SaleDetailsVariables, options?: useDataConnectQueryOptions<SaleDetailsData>): UseDataConnectQueryResult<SaleDetailsData, SaleDetailsVariables>;

export function useListCategories(vars: ListCategoriesVariables, options?: useDataConnectQueryOptions<ListCategoriesData>): UseDataConnectQueryResult<ListCategoriesData, ListCategoriesVariables>;
export function useListCategories(dc: DataConnect, vars: ListCategoriesVariables, options?: useDataConnectQueryOptions<ListCategoriesData>): UseDataConnectQueryResult<ListCategoriesData, ListCategoriesVariables>;

export function useListSubcategories(vars: ListSubcategoriesVariables, options?: useDataConnectQueryOptions<ListSubcategoriesData>): UseDataConnectQueryResult<ListSubcategoriesData, ListSubcategoriesVariables>;
export function useListSubcategories(dc: DataConnect, vars: ListSubcategoriesVariables, options?: useDataConnectQueryOptions<ListSubcategoriesData>): UseDataConnectQueryResult<ListSubcategoriesData, ListSubcategoriesVariables>;

export function useCategoryOptions(vars?: CategoryOptionsVariables, options?: useDataConnectQueryOptions<CategoryOptionsData>): UseDataConnectQueryResult<CategoryOptionsData, CategoryOptionsVariables>;
export function useCategoryOptions(dc: DataConnect, vars?: CategoryOptionsVariables, options?: useDataConnectQueryOptions<CategoryOptionsData>): UseDataConnectQueryResult<CategoryOptionsData, CategoryOptionsVariables>;

export function useListBranches(vars: ListBranchesVariables, options?: useDataConnectQueryOptions<ListBranchesData>): UseDataConnectQueryResult<ListBranchesData, ListBranchesVariables>;
export function useListBranches(dc: DataConnect, vars: ListBranchesVariables, options?: useDataConnectQueryOptions<ListBranchesData>): UseDataConnectQueryResult<ListBranchesData, ListBranchesVariables>;

export function useListSuppliers(vars: ListSuppliersVariables, options?: useDataConnectQueryOptions<ListSuppliersData>): UseDataConnectQueryResult<ListSuppliersData, ListSuppliersVariables>;
export function useListSuppliers(dc: DataConnect, vars: ListSuppliersVariables, options?: useDataConnectQueryOptions<ListSuppliersData>): UseDataConnectQueryResult<ListSuppliersData, ListSuppliersVariables>;

export function useListCustomers(vars: ListCustomersVariables, options?: useDataConnectQueryOptions<ListCustomersData>): UseDataConnectQueryResult<ListCustomersData, ListCustomersVariables>;
export function useListCustomers(dc: DataConnect, vars: ListCustomersVariables, options?: useDataConnectQueryOptions<ListCustomersData>): UseDataConnectQueryResult<ListCustomersData, ListCustomersVariables>;

export function useListProducts(vars: ListProductsVariables, options?: useDataConnectQueryOptions<ListProductsData>): UseDataConnectQueryResult<ListProductsData, ListProductsVariables>;
export function useListProducts(dc: DataConnect, vars: ListProductsVariables, options?: useDataConnectQueryOptions<ListProductsData>): UseDataConnectQueryResult<ListProductsData, ListProductsVariables>;

export function useRegistrationOptions(vars?: RegistrationOptionsVariables, options?: useDataConnectQueryOptions<RegistrationOptionsData>): UseDataConnectQueryResult<RegistrationOptionsData, RegistrationOptionsVariables>;
export function useRegistrationOptions(dc: DataConnect, vars?: RegistrationOptionsVariables, options?: useDataConnectQueryOptions<RegistrationOptionsData>): UseDataConnectQueryResult<RegistrationOptionsData, RegistrationOptionsVariables>;

export function useProductComponents(vars: ProductComponentsVariables, options?: useDataConnectQueryOptions<ProductComponentsData>): UseDataConnectQueryResult<ProductComponentsData, ProductComponentsVariables>;
export function useProductComponents(dc: DataConnect, vars: ProductComponentsVariables, options?: useDataConnectQueryOptions<ProductComponentsData>): UseDataConnectQueryResult<ProductComponentsData, ProductComponentsVariables>;

export function useProductPromotions(vars: ProductPromotionsVariables, options?: useDataConnectQueryOptions<ProductPromotionsData>): UseDataConnectQueryResult<ProductPromotionsData, ProductPromotionsVariables>;
export function useProductPromotions(dc: DataConnect, vars: ProductPromotionsVariables, options?: useDataConnectQueryOptions<ProductPromotionsData>): UseDataConnectQueryResult<ProductPromotionsData, ProductPromotionsVariables>;

export function usePlatformAdminWorkspace(vars: PlatformAdminWorkspaceVariables, options?: useDataConnectQueryOptions<PlatformAdminWorkspaceData>): UseDataConnectQueryResult<PlatformAdminWorkspaceData, PlatformAdminWorkspaceVariables>;
export function usePlatformAdminWorkspace(dc: DataConnect, vars: PlatformAdminWorkspaceVariables, options?: useDataConnectQueryOptions<PlatformAdminWorkspaceData>): UseDataConnectQueryResult<PlatformAdminWorkspaceData, PlatformAdminWorkspaceVariables>;

export function useStockWorkspace(vars: StockWorkspaceVariables, options?: useDataConnectQueryOptions<StockWorkspaceData>): UseDataConnectQueryResult<StockWorkspaceData, StockWorkspaceVariables>;
export function useStockWorkspace(dc: DataConnect, vars: StockWorkspaceVariables, options?: useDataConnectQueryOptions<StockWorkspaceData>): UseDataConnectQueryResult<StockWorkspaceData, StockWorkspaceVariables>;

export function useDailyProfitDashboard(vars: DailyProfitDashboardVariables, options?: useDataConnectQueryOptions<DailyProfitDashboardData>): UseDataConnectQueryResult<DailyProfitDashboardData, DailyProfitDashboardVariables>;
export function useDailyProfitDashboard(dc: DataConnect, vars: DailyProfitDashboardVariables, options?: useDataConnectQueryOptions<DailyProfitDashboardData>): UseDataConnectQueryResult<DailyProfitDashboardData, DailyProfitDashboardVariables>;

export function useStockOperationDetails(vars: StockOperationDetailsVariables, options?: useDataConnectQueryOptions<StockOperationDetailsData>): UseDataConnectQueryResult<StockOperationDetailsData, StockOperationDetailsVariables>;
export function useStockOperationDetails(dc: DataConnect, vars: StockOperationDetailsVariables, options?: useDataConnectQueryOptions<StockOperationDetailsData>): UseDataConnectQueryResult<StockOperationDetailsData, StockOperationDetailsVariables>;

export function useFinancialIndicatorsDashboard(vars: FinancialIndicatorsDashboardVariables, options?: useDataConnectQueryOptions<FinancialIndicatorsDashboardData>): UseDataConnectQueryResult<FinancialIndicatorsDashboardData, FinancialIndicatorsDashboardVariables>;
export function useFinancialIndicatorsDashboard(dc: DataConnect, vars: FinancialIndicatorsDashboardVariables, options?: useDataConnectQueryOptions<FinancialIndicatorsDashboardData>): UseDataConnectQueryResult<FinancialIndicatorsDashboardData, FinancialIndicatorsDashboardVariables>;

export function useOperationalAnalyticsDashboard(vars: OperationalAnalyticsDashboardVariables, options?: useDataConnectQueryOptions<OperationalAnalyticsDashboardData>): UseDataConnectQueryResult<OperationalAnalyticsDashboardData, OperationalAnalyticsDashboardVariables>;
export function useOperationalAnalyticsDashboard(dc: DataConnect, vars: OperationalAnalyticsDashboardVariables, options?: useDataConnectQueryOptions<OperationalAnalyticsDashboardData>): UseDataConnectQueryResult<OperationalAnalyticsDashboardData, OperationalAnalyticsDashboardVariables>;

export function useRecoverPlatformAdministrator(options?: useDataConnectMutationOptions<RecoverPlatformAdministratorData, FirebaseError, void>): UseDataConnectMutationResult<RecoverPlatformAdministratorData, undefined>;
export function useRecoverPlatformAdministrator(dc: DataConnect, options?: useDataConnectMutationOptions<RecoverPlatformAdministratorData, FirebaseError, void>): UseDataConnectMutationResult<RecoverPlatformAdministratorData, undefined>;
