import{useCallback,useEffect,useMemo,useRef,useState,type FormEvent}from'react'
import{getDataConnect}from'firebase/data-connect'
import{Link}from'react-router-dom'
import{cancelSale,connectorConfig,ensureSalesDefaults,postSale,saleDetails,salesWorkspace}from'@insightpad/dataconnect'
import{firebaseApp}from'../lib/firebase'
import{useAuth}from'../auth/useAuth'
import{useDialogAccessibility}from'../hooks/useDialogAccessibility'
import{cents,lineTotal,money,quantity,saleTotals,upsertCart,validateCheckout,type CartItem,type PaymentInput}from'../utils/sales'
import{markPendingFailure,pendingSales,queueSale,removePendingSale}from'../utils/salesOffline'

const dc=getDataConnect(firebaseApp,connectorConfig)
type Branch={id:string;name:string;internalCode?:string};type Customer={id:string;name:string;cpf?:string;email?:string;phone?:string};type Method={id:string;code:string;name:string;requiresChange:boolean}
type Product={id:string;name:string;internalCode?:string;ean?:string;weightedProduct:boolean;bundleProduct:boolean;allowNegativeStock:boolean;listPriceCents:string;effectivePriceCents:string;costPriceCents:string;stock:number}
type Workspace={branches:Branch[];customers:Customer[];paymentMethods:Method[];products:Product[];openSession?:{id:string;openedAt:string}|null}
const empty:Workspace={branches:[],customers:[],paymentMethods:[],products:[]}

export function PointOfSalePage(){const permission=useAuth().permissions.CAIXA
 const[workspace,setWorkspace]=useState<Workspace>(empty),[branchId,setBranchId]=useState(localStorage.getItem('insightpad.sale.branch')??''),[cart,setCart]=useState<CartItem[]>([]),[term,setTerm]=useState(''),[qty,setQty]=useState(1),[selectedId,setSelectedId]=useState(''),[busy,setBusy]=useState(true),[notice,setNotice]=useState(''),[checkout,setCheckout]=useState(false),[customerId,setCustomerId]=useState(''),[discount,setDiscount]=useState(''),[surcharge,setSurcharge]=useState(''),[payments,setPayments]=useState<PaymentInput[]>([{paymentMethodId:'',amountCents:0,sequence:1}]),[pending,setPending]=useState(0),[online,setOnline]=useState(navigator.onLine),[stockProduct,setStockProduct]=useState<Product|null>(null),[confirmClear,setConfirmClear]=useState(false),[lastReceipt,setLastReceipt]=useState<Record<string,unknown>|null>(null),[correctionId,setCorrectionId]=useState('')
 const searchRef=useRef<HTMLInputElement>(null);useDialogAccessibility(checkout,()=>setCheckout(false));useDialogAccessibility(Boolean(stockProduct),()=>setStockProduct(null));useDialogAccessibility(confirmClear,()=>setConfirmClear(false))
 const load=useCallback(async()=>{setBusy(true);try{await ensureSalesDefaults(dc);const result=await salesWorkspace(dc,{branchId:branchId||null,requestKey:crypto.randomUUID()});const data=((result.data._select??[])[0] as{data?:Workspace}|undefined)?.data??empty;setWorkspace(data);if(!branchId&&data.branches.length===1)setBranchId(data.branches[0].id)}catch(error){console.error(error);setNotice('Não foi possível carregar o caixa. Verifique sua conexão e permissão.')}finally{setBusy(false)}},[branchId])
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);useEffect(()=>{localStorage.setItem('insightpad.sale.branch',branchId)},[branchId]);useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),7000);return()=>clearTimeout(timer)},[notice]);useEffect(()=>{void pendingSales().then(rows=>setPending(rows.length))},[])
 const filtered=useMemo(()=>{const q=term.trim().toLocaleLowerCase('pt-BR');return q?workspace.products.filter(p=>[p.name,p.internalCode,p.ean].some(v=>v?.toLocaleLowerCase('pt-BR').includes(q))).slice(0,30):workspace.products.slice(0,30)},[term,workspace.products])
 useEffect(()=>{if(!workspace.products.length||correctionId)return;const raw=sessionStorage.getItem('insightpad.sale.correction');if(!raw)return;sessionStorage.removeItem('insightpad.sale.correction');const saleId=String((JSON.parse(raw)as{saleId?:string}).saleId??'');if(!saleId)return;void saleDetails(dc,{saleId,requestKey:crypto.randomUUID()}).then(result=>{const box=((result.data._select??[])[0]as{data?:{sale:Record<string,unknown>;items:Array<Record<string,unknown>>;payments:Array<Record<string,unknown>>}})?.data;if(!box)return;setCorrectionId(saleId);setBranchId(String(box.sale.branch_id??''));setCustomerId(String(box.sale.customer_id??''));setDiscount(money(Number(box.sale.discount_cents??0)));setSurcharge(money(Number(box.sale.surcharge_cents??0)));setCart(box.items.flatMap(item=>{const product=workspace.products.find(p=>p.id===item.productId);return product?[{productId:product.id,name:product.name,quantity:Number(item.quantity),unitPriceCents:Number(item.unitSalePriceCents),listPriceCents:Number(item.unitListPriceCents),costPriceCents:Number(item.unitCostCents),weightedProduct:product.weightedProduct,bundleProduct:product.bundleProduct,stock:Number(product.stock),allowNegativeStock:product.allowNegativeStock}]:[]}));setPayments(box.payments.map((p,index)=>({paymentMethodId:String(p.paymentMethodId),amountCents:Number(p.amountCents),sequence:index+1,externalReference:String(p.externalReference??'')})));setNotice('Venda carregada para correção. Ao concluir, a original será cancelada e o estoque recalculado.')}).catch(()=>setNotice('Não foi possível carregar a venda para correção.'))},[workspace.products,correctionId])
 const selected=workspace.products.find(p=>p.id===selectedId)||filtered[0],totals=saleTotals(cart,cents(discount),cents(surcharge)),paid=payments.reduce((sum,p)=>sum+p.amountCents,0),change=Math.max(0,paid-totals.totalCents),remaining=Math.max(0,totals.totalCents-paid)
 function add(product=selected){if(!branchId){setNotice('Selecione a filial antes de iniciar a venda.');return}if(!product){setNotice('Localize e selecione um produto.');return}const q=quantity(qty,product.weightedProduct);if(q<=0){setNotice('Informe uma quantidade maior que zero.');return}if(!product.allowNegativeStock&&!product.bundleProduct&&product.stock<q){setNotice(`Saldo insuficiente: existem ${product.stock} unidade(s) nesta filial.`);return}setCart(current=>upsertCart(current,{productId:product.id,name:product.name,quantity:q,unitPriceCents:Number(product.effectivePriceCents),listPriceCents:Number(product.listPriceCents),costPriceCents:Number(product.costPriceCents),weightedProduct:product.weightedProduct,bundleProduct:product.bundleProduct,stock:Number(product.stock),allowNegativeStock:product.allowNegativeStock}));setTerm('');setSelectedId('');setQty(1);requestAnimationFrame(()=>searchRef.current?.focus())}
 function openCheckout(){if(!cart.length){setNotice('Adicione produtos antes de seguir para o pagamento.');return}const first=workspace.paymentMethods[0];setPayments([{paymentMethodId:first?.id??'',amountCents:totals.totalCents,sequence:1}]);setCheckout(true)}
 const sync=useCallback(async()=>{if(!navigator.onLine)return;const rows=await pendingSales();for(const row of rows){try{await postSale(dc,{payload:row.payload});const replaced=String(row.payload.replacesSaleId??'');if(replaced)await cancelSale(dc,{saleId:replaced,reason:`Venda corrigida e substituída pela operação ${row.clientOperationId}`});await removePendingSale(row.clientOperationId)}catch(error){await markPendingFailure(row,error instanceof Error?error.message:'Falha desconhecida')}}setPending((await pendingSales()).length)},[])
 useEffect(()=>{const status=()=>{setOnline(navigator.onLine);if(navigator.onLine)void sync()};addEventListener('online',status);addEventListener('offline',status);return()=>{removeEventListener('online',status);removeEventListener('offline',status)}},[sync])
 async function finish(event:FormEvent){event.preventDefault();const changeIds=new Set(workspace.paymentMethods.filter(m=>m.requiresChange).map(m=>m.id)),error=validateCheckout(cart,payments,cents(discount),cents(surcharge),changeIds);if(error){setNotice(error);return}const clientOperationId=crypto.randomUUID(),payload={clientOperationId,branchId,customerId:customerId||null,cashSessionId:workspace.openSession?.id??null,discountCents:cents(discount),surchargeCents:cents(surcharge),items:cart.map(item=>({product_id:item.productId,quantity:item.quantity,requested_price:item.unitPriceCents})),payments:payments.map((p,index)=>({payment_method_id:p.paymentMethodId,amount_cents:p.amountCents,sequence:index+1,external_reference:p.externalReference??null}))};setBusy(true)
  try{const correctedPayload={...payload,replacesSaleId:correctionId||null};if(online){const posted=await postSale(dc,{payload:correctedPayload});if(!posted.data._execute)throw new Error('Venda rejeitada pelas regras do servidor.');if(correctionId)await cancelSale(dc,{saleId:correctionId,reason:`Venda corrigida e substituída pela operação ${clientOperationId}`})}else{await queueSale(correctedPayload);setPending(value=>value+1)}setLastReceipt({id:clientOperationId,branch:workspace.branches.find(b=>b.id===branchId)?.name,customer:workspace.customers.find(c=>c.id===customerId)?.name??'Consumidor final',items:[...cart],...totals,changeCents:change,date:new Date().toISOString()});setCart([]);setCorrectionId('');setCheckout(false);setDiscount('');setSurcharge('');setCustomerId('');setNotice(online?'Venda concluída e estoque atualizado.':'Venda salva com segurança. Será sincronizada quando a conexão retornar.');await load()}catch(err){console.error(err);setNotice('Venda não concluída. Confira estoque, pagamentos, caixa aberto e dados informados.')}finally{setBusy(false)}}
 function printReceipt(){if(!lastReceipt)return;const receipt=lastReceipt as{id:string;branch:string;customer:string;items:CartItem[];subtotalCents:number;discountCents:number;surchargeCents:number;totalCents:number;changeCents:number;date:string};const html=`<html><head><title>Venda ${receipt.id}</title><style>body{font:14px monospace;max-width:320px;margin:auto}h1{text-align:center;font-size:20px}table{width:100%;border-collapse:collapse}td{padding:4px 0;border-bottom:1px dashed #999}.right{text-align:right}</style></head><body><h1>INSIGHT PAD</h1><p>${receipt.branch}<br>${new Date(receipt.date).toLocaleString('pt-BR')}<br>${receipt.customer}</p><table>${receipt.items.map(i=>`<tr><td>${i.name}<br>${i.quantity} x ${money(i.unitPriceCents)}</td><td class="right">${money(lineTotal(i))}</td></tr>`).join('')}</table><p>Total: <b>${money(receipt.totalCents)}</b><br>Troco: ${money(receipt.changeCents)}</p><small>${receipt.id}</small><script>print();close()</script></body></html>`;const win=open('','receipt','width=420,height=650');win?.document.write(html);win?.document.close()}
 return <section className="sales-page pos-page"><header className="sales-title"><div><span className="eyebrow">Vendas{correctionId?' · Correção':''}</span><h1>{correctionId?'Corrigir venda':'Frente de caixa'}</h1></div><div className="sales-header-actions"><span className={`connection ${online?'online':'offline'}`}><i/>{online?'Online':'Offline'}{pending>0&&` · ${pending} pendente(s)`}</span>{pending>0&&online&&<button onClick={()=>void sync()}>Sincronizar</button>}<Link className="catalog-back" to="/modulos/vendas"><span className="material-symbols-rounded">arrow_back</span>Voltar</Link></div></header>
 {notice&&<div className="master-toast" role="alert"><span className="material-symbols-rounded">info</span><strong>{notice}</strong><button onClick={()=>setNotice('')}>×</button></div>}
 <div className="pos-layout"><aside className="pos-entry"><label>Filial<select value={branchId} onChange={e=>{if(cart.length){setNotice('Limpe o carrinho antes de trocar de filial.');return}setBranchId(e.target.value)}}><option value="">Selecione</option>{workspace.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Produto<input ref={searchRef} autoFocus value={term} onChange={e=>setTerm(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();add()}}} placeholder="Código, EAN ou nome"/></label><div className="product-results">{filtered.map(p=><button className={selected?.id===p.id?'active':''} key={p.id} onClick={()=>setSelectedId(p.id)}><span><strong>{p.name}</strong><small>{p.internalCode||p.ean||'Sem código'} · {p.bundleProduct?'Combo':p.weightedProduct?'Pesável':'Unidade'}</small></span><span><b>{money(p.effectivePriceCents)}</b><small>Saldo {p.stock}</small></span></button>)}</div>{selected&&<div className="selected-product"><div><strong>{selected.name}</strong><button onClick={()=>setStockProduct(selected)}>Estoque por filial</button></div><label>Quantidade<input type="number" min={selected.weightedProduct?0.001:1} step={selected.weightedProduct?0.001:1} value={qty} onChange={e=>setQty(Number(e.target.value))}/></label><button className="catalog-primary" onClick={()=>add()}>Adicionar ao carrinho</button></div>}</aside>
 <main className="pos-cart"><div className="pos-cart-head"><div><strong>Carrinho</strong><small>{cart.length} produto(s)</small></div>{cart.length>0&&<button className="danger" onClick={()=>setConfirmClear(true)}>Limpar</button>}</div><div className="pos-cart-scroll">{!cart.length?<div className="empty-state"><span className="material-symbols-rounded">shopping_cart</span><p>Leia um código ou pesquise um produto para começar.</p></div>:cart.map(item=><article key={item.productId}><div><strong>{item.name}</strong><small>{item.bundleProduct?'COMBO · ':''}{money(item.unitPriceCents)} por unidade</small></div><label><span>Qtd.</span><input type="number" min={item.weightedProduct?0.001:1} step={item.weightedProduct?0.001:1} value={item.quantity} onChange={e=>setCart(rows=>rows.map(row=>row.productId===item.productId?{...row,quantity:quantity(Number(e.target.value),row.weightedProduct)}:row))}/></label><b>{money(lineTotal(item))}</b><button aria-label={`Remover ${item.name}`} onClick={()=>setCart(rows=>rows.filter(row=>row.productId!==item.productId))}>×</button></article>)}</div><footer className="pos-total"><span>Subtotal <b>{money(totals.subtotalCents)}</b></span><strong>Total <b>{money(totals.totalCents)}</b></strong><button className="catalog-primary" disabled={!permission?.canCreate||!cart.length} onClick={openCheckout}>Ir para pagamento <kbd>F9</kbd></button>{lastReceipt&&<button onClick={printReceipt}>Imprimir último comprovante</button>}</footer></main></div>
 {checkout&&<div className="catalog-backdrop"><section className="catalog-modal sales-modal" role="dialog" aria-modal="true"><header><div><span className="eyebrow">Finalização</span><h2>Pagamento</h2></div><button onClick={()=>setCheckout(false)}>×</button></header><form onSubmit={finish}><div className="checkout-grid"><label>Cliente (opcional)<select value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Consumidor final</option>{workspace.customers.map(c=><option key={c.id} value={c.id}>{c.name}{c.cpf?` · ${c.cpf}`:''}</option>)}</select></label><label>Desconto<input inputMode="numeric" value={discount} onChange={e=>setDiscount(money(cents(e.target.value)))} /></label><label>Acréscimo<input inputMode="numeric" value={surcharge} onChange={e=>setSurcharge(money(cents(e.target.value)))} /></label></div><div className="checkout-summary"><span>Subtotal <b>{money(totals.subtotalCents)}</b></span><span>Desconto <b>- {money(totals.discountCents)}</b></span><span>Acréscimo <b>{money(totals.surchargeCents)}</b></span><strong>Total <b>{money(totals.totalCents)}</b></strong></div><section className="payments"><header><strong>Formas de pagamento</strong><button type="button" onClick={()=>setPayments(rows=>[...rows,{paymentMethodId:'',amountCents:remaining,sequence:rows.length+1}])}>+ Dividir pagamento</button></header>{payments.map((p,index)=><div className="payment-row" key={index}><select value={p.paymentMethodId} onChange={e=>setPayments(rows=>rows.map((row,i)=>i===index?{...row,paymentMethodId:e.target.value}:row))}><option value="">Selecione</option>{workspace.paymentMethods.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><input inputMode="numeric" value={money(p.amountCents)} onChange={e=>setPayments(rows=>rows.map((row,i)=>i===index?{...row,amountCents:cents(e.target.value)}:row))}/><input placeholder="Referência (opcional)" value={p.externalReference??''} onChange={e=>setPayments(rows=>rows.map((row,i)=>i===index?{...row,externalReference:e.target.value}:row))}/>{payments.length>1&&<button type="button" onClick={()=>setPayments(rows=>rows.filter((_,i)=>i!==index))}>×</button>}</div>)}</section><div className="payment-balance"><span>Pago <b>{money(paid)}</b></span><span>Falta <b>{money(remaining)}</b></span><span>Troco <b>{money(change)}</b></span></div><footer><button type="button" onClick={()=>setCheckout(false)}>Cancelar</button><button className="catalog-primary" disabled={busy}>Concluir venda</button></footer></form></section></div>}
 {stockProduct&&<div className="catalog-backdrop"><section className="catalog-confirm"><span className="material-symbols-rounded">inventory</span><h2>{stockProduct.name}</h2><p>Saldo na filial selecionada: <strong>{stockProduct.stock}</strong></p><footer><button className="catalog-primary" onClick={()=>setStockProduct(null)}>Fechar</button></footer></section></div>}{confirmClear&&<div className="catalog-backdrop"><section className="catalog-confirm"><span className="material-symbols-rounded">delete_sweep</span><h2>Limpar carrinho?</h2><p>Todos os itens serão removidos.</p><footer><button onClick={()=>setConfirmClear(false)}>Voltar</button><button className="danger" onClick={()=>{setCart([]);setConfirmClear(false)}}>Limpar</button></footer></section></div>}{busy&&<div className="operation-loading"><div className="loading-orbit"><div className="brand-mark"><span>Insight Pad</span></div></div><p>Processando...</p></div>}</section>
}
