import{useCallback,useEffect,useMemo,useState}from'react'
import{getDataConnect}from'firebase/data-connect'
import{Link}from'react-router-dom'
import{cancelSale,connectorConfig,listSales,postSale,saleDetails,salesWorkspace}from'@insightpad/dataconnect'
import{firebaseApp}from'../lib/firebase'
import{useAuth}from'../auth/useAuth'
import{useDialogAccessibility}from'../hooks/useDialogAccessibility'
import{AppLoading,AppToast,DateRangePicker,SearchableMultiSelect,type Notice}from'../components/SalesUi'
import{SalesCorrectionModal}from'../components/SalesCorrectionModal'
import{csvSafe}from'../utils/registration'
import{cents,money}from'../utils/sales'
const dc=getDataConnect(firebaseApp,connectorConfig),LIMIT=5000
type Sale={id:string;clientOperationId:string;status:string;subtotalCents:string;discountCents:string;surchargeCents:string;totalCents:string;changeCents:string;soldAt:string;cancelledAt?:string;cancellationReason?:string;createdByUid:string;branchId:string;branchName:string;customerId?:string;customerName:string;itemCount:number;paymentMethods:string}
type Details={sale:Record<string,unknown>;branch:Record<string,unknown>;customer?:Record<string,unknown>;items:Array<Record<string,unknown>>;payments:Array<Record<string,unknown>>}
type Workspace={branches:Array<{id:string;name:string}>;customers:Array<{id:string;name:string}>;paymentMethods:Array<{id:string;name:string}>;products:Array<{id:string;name:string}>}
export function SalesManagementPage(){const permission=useAuth().permissions.GESTAO_VENDAS;const[rows,setRows]=useState<Sale[]>([]),[workspace,setWorkspace]=useState<Workspace>({branches:[],customers:[],paymentMethods:[],products:[]}),[search,setSearch]=useState(''),[filters,setFilters]=useState<Record<string,unknown>>({}),[draftFilters,setDraftFilters]=useState<Record<string,unknown>>({}),[filterModal,setFilterModal]=useState(false),[details,setDetails]=useState<Details|null>(null),[correctionDetails,setCorrectionDetails]=useState<Details|null>(null),[busy,setBusy]=useState(true),[notice,setNotice]=useState(''),[cancel,setCancel]=useState<Sale|null>(null),[reason,setReason]=useState('')
 useDialogAccessibility(filterModal,()=>setFilterModal(false));useDialogAccessibility(Boolean(details),()=>setDetails(null));useDialogAccessibility(Boolean(cancel),()=>setCancel(null));useDialogAccessibility(Boolean(correctionDetails),()=>setCorrectionDetails(null));useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),7000);return()=>clearTimeout(timer)},[notice])
 const load=useCallback(async()=>{setBusy(true);try{const queryFilters={...filters,search:search.trim()};const[result,options]=await Promise.all([listSales(dc,{filters:queryFilters,limit:LIMIT,offset:0,requestKey:crypto.randomUUID()}),salesWorkspace(dc,{branchId:null,requestKey:crypto.randomUUID()})]);setRows((result.data._select??[]) as Sale[]);setWorkspace((((options.data._select??[])[0] as{data?:Workspace})?.data)??{branches:[],customers:[],paymentMethods:[],products:[]})}catch(error){console.error(error);setNotice('Não foi possível atualizar as vendas.')}finally{setBusy(false)}},[filters,search]);useEffect(()=>{const timer=setTimeout(()=>void load(),300);return()=>clearTimeout(timer)},[load])
 async function openDetails(row:Sale){setBusy(true);try{const result=await saleDetails(dc,{saleId:row.id,requestKey:crypto.randomUUID()});setDetails(((result.data._select??[])[0] as{data:Details}).data)}catch(error){console.error(error);setNotice('Não foi possível abrir os detalhes da venda.')}finally{setBusy(false)}}
 async function confirmCancel(){if(!cancel||reason.trim().length<5){setNotice('Informe um motivo de cancelamento com pelo menos 5 caracteres.');return}setBusy(true);try{const result=await cancelSale(dc,{saleId:cancel.id,reason:reason.trim()});if(!result.data._execute)throw new Error();setCancel(null);setReason('');setNotice('Venda cancelada e estoque estornado com sucesso.');await load()}catch(error){console.error(error);setNotice('A venda não foi cancelada. Confira status e permissão.')}finally{setBusy(false)}}
 async function correction(row:Sale){setBusy(true);try{const result=await saleDetails(dc,{saleId:row.id,requestKey:crypto.randomUUID()});setCorrectionDetails(((result.data._select??[])[0] as{data:Details}).data)}catch{setNotice('Não foi possível carregar a venda para correção.')}finally{setBusy(false)}}
 function correctedTotal(current:Details){const subtotal=current.items.reduce((sum,item)=>sum+Math.round(Number(item.quantity)*Number(item.unitSalePriceCents)),0);return Math.max(0,subtotal-Number(current.sale.discount_cents??0)+Number(current.sale.surcharge_cents??0))}
 function updateCorrectionItem(index:number,quantity:number){setCorrectionDetails(current=>{if(!current)return current;const next={...current,items:current.items.map((item,i)=>i===index?{...item,quantity}:item)},total=correctedTotal(next),payments=next.payments.map(payment=>({...payment}));if(payments.length===1)payments[0].amountCents=total;else if(payments.length===2)payments[1].amountCents=Math.max(0,total-Number(payments[0].amountCents));return{...next,payments}})}
 function updateCorrectionPayment(index:number,amountCents:number){setCorrectionDetails(current=>{if(!current)return current;const total=correctedTotal(current),payments=current.payments.map((payment,i)=>i===index?{...payment,amountCents}:payment);if(payments.length===2){const other=index===0?1:0;payments[other]={...payments[other],amountCents:Math.max(0,total-amountCents)}}return{...current,payments}})}
 async function saveCorrection(){if(!correctionDetails)return;const originalId=String(correctionDetails.sale.id),operationId=crypto.randomUUID(),payload={clientOperationId:operationId,branchId:String(correctionDetails.sale.branch_id),customerId:correctionDetails.sale.customer_id||null,cashSessionId:null,replacesSaleId:originalId,discountCents:Number(correctionDetails.sale.discount_cents??0),surchargeCents:Number(correctionDetails.sale.surcharge_cents??0),items:correctionDetails.items.map(item=>({product_id:item.productId,quantity:Number(item.quantity),requested_price:Number(item.unitSalePriceCents)})),payments:correctionDetails.payments.map((payment,index)=>({payment_method_id:payment.paymentMethodId,amount_cents:Number(payment.amountCents),sequence:index+1,external_reference:payment.externalReference??null}))};setBusy(true);try{const posted=await postSale(dc,{payload});if(!posted.data._execute)throw new Error();await cancelSale(dc,{saleId:originalId,reason:`Venda corrigida e substituída pela operação ${operationId}`});setCorrectionDetails(null);setNotice('Venda corrigida e estoque recalculado com sucesso.');await load()}catch(error){console.error(error);setNotice('Não foi possível concluir a correção. Confira quantidades, pagamentos e estoque.')}finally{setBusy(false)}}
 const activeCount=useMemo(()=>Object.values(filters).filter(value=>Array.isArray(value)?value.length:Boolean(value)).length,[filters]);function exportCsv(){const keys=['id','soldAt','status','branchName','customerName','itemCount','subtotalCents','discountCents','surchargeCents','totalCents','changeCents','paymentMethods','createdByUid','cancelledAt','cancellationReason','clientOperationId'];const labels=['ID','Data','Status','Filial','Cliente','Itens','Subtotal','Desconto','Acréscimo','Total','Troco','Pagamentos','Usuário','Cancelada em','Motivo','Operação'];const line=(r:Sale)=>keys.map(key=>{const value=r[key as keyof Sale];const out=/Cents$/.test(key)?money(String(value)):String(value??'');return`"${csvSafe(out).replaceAll('"','""')}"`}).join(';');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([`\uFEFF${labels.join(';')}\n${rows.map(line).join('\n')}`],{type:'text/csv'}));a.download='vendas-completo.csv';a.click();URL.revokeObjectURL(a.href)}
 const toast:Notice|null=notice?{text:notice,type:/sucesso|cancelada/i.test(notice)?'success':'error'}:null
 return <section className="catalog-page sales-page"><header className="sales-title"><div><span className="eyebrow">Vendas</span><h1>Registros de venda</h1></div><div className="catalog-header-actions"><Link className="catalog-back" to="/modulos/vendas"><span className="material-symbols-rounded">arrow_back</span>Voltar</Link>{permission?.canCreate&&<Link className="catalog-primary" to="/vendas/frente-de-caixa">+ Nova venda</Link>}</div></header><AppToast notice={toast} onClose={()=>setNotice('')}/><div className="catalog-panel"><div className="catalog-toolbar"><label><span className="material-symbols-rounded">search</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ID ou cliente..."/></label><button onClick={()=>{setDraftFilters(filters);setFilterModal(true)}}><span className="material-symbols-rounded">tune</span>Pesquisa avançada{activeCount>0&&<b>{activeCount}</b>}</button>{permission?.canExport&&<button onClick={exportCsv}>Exportar CSV</button>}</div><div className="catalog-scroll"><div className="catalog-table"><table><thead><tr><th>Venda</th><th>Data</th><th>Cliente</th><th>Filial</th><th>Total</th><th>Pagamento</th><th>Status</th><th>Ações</th><th>Itens</th><th>Subtotal</th><th>Desconto</th><th>Acréscimo</th><th>Troco</th><th>Usuário</th><th>Operação</th></tr></thead><tbody>{rows.map(row=><tr key={row.id} className={row.status==='CANCELLED'?'is-inactive':''}><td>{row.id.slice(0,8).toUpperCase()}</td><td>{new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(row.soldAt))}</td><td>{row.customerName}</td><td>{row.branchName}</td><td><strong>{money(row.totalCents)}</strong></td><td>{row.paymentMethods||'—'}</td><td><span className={`catalog-status catalog-status--${row.status==='COMPLETED'?'active':'inactive'}`}><i/>{row.status==='COMPLETED'?'Concluída':'Cancelada'}</span></td><td><div className="catalog-actions"><button onClick={()=>void openDetails(row)}>Detalhes</button>{row.status==='COMPLETED'&&permission?.canUpdate&&<button onClick={()=>correction(row)}>Corrigir</button>}{row.status==='COMPLETED'&&permission?.canDelete&&<button className="danger" onClick={()=>setCancel(row)}>Cancelar</button>}</div></td><td>{row.itemCount}</td><td>{money(row.subtotalCents)}</td><td>{money(row.discountCents)}</td><td>{money(row.surchargeCents)}</td><td>{money(row.changeCents)}</td><td>{row.createdByUid}</td><td>{row.clientOperationId}</td></tr>)}</tbody></table></div></div></div>
 {filterModal&&<div className="catalog-backdrop"><section className="catalog-modal master-modal advanced-search-modal sales-filter-modal" role="dialog" aria-modal="true" aria-label="Pesquisa avançada de vendas"><header><div><span className="eyebrow">Pesquisa</span><h2>Filtros avançados</h2></div><button aria-label="Fechar pesquisa" onClick={()=>setFilterModal(false)}>×</button></header><form onSubmit={event=>{event.preventDefault();setFilters(draftFilters);setFilterModal(false)}}><div className="catalog-filter-body"><div className="master-section-title"><span className="material-symbols-rounded">manage_search</span><div><strong>Refine os registros de venda</strong><small>Selecione um ou mais valores e defina o período desejado.</small></div></div><div className="master-form-grid filter-grid sales-filter-grid"><SearchableMultiSelect label="Filiais" options={workspace.branches.map(item=>({value:item.id,label:item.name}))} value={(draftFilters.branchIds as string[])??[]} onChange={value=>setDraftFilters({...draftFilters,branchIds:value})}/><SearchableMultiSelect label="Clientes" options={workspace.customers.map(item=>({value:item.id,label:item.name}))} value={(draftFilters.customerIds as string[])??[]} onChange={value=>setDraftFilters({...draftFilters,customerIds:value})}/><SearchableMultiSelect label="Status" options={[{value:'COMPLETED',label:'Concluída'},{value:'CANCELLED',label:'Cancelada'}]} value={(draftFilters.statuses as string[])??[]} onChange={value=>setDraftFilters({...draftFilters,statuses:value})}/><DateRangePicker from={String(draftFilters.dateFrom??'')} to={String(draftFilters.dateTo??'')} onChange={(dateFrom,dateTo)=>setDraftFilters({...draftFilters,dateFrom,dateTo})}/><label><span>Valor mínimo</span><input inputMode="numeric" value={draftFilters.minCents?money(Number(draftFilters.minCents)):''} onChange={event=>setDraftFilters({...draftFilters,minCents:String(cents(event.target.value))})} placeholder="Em centavos"/></label><label><span>Valor máximo</span><input inputMode="numeric" value={draftFilters.maxCents?money(Number(draftFilters.maxCents)):''} onChange={event=>setDraftFilters({...draftFilters,maxCents:String(cents(event.target.value))})} placeholder="Em centavos"/></label></div></div><footer><button type="button" onClick={()=>setDraftFilters({})}>Limpar filtros</button><button type="button" className="catalog-modal-cancel" onClick={()=>setFilterModal(false)}>Cancelar</button><button className="catalog-primary">Aplicar filtros</button></footer></form></section></div>}
 {correctionDetails&&<SalesCorrectionModal details={correctionDetails} onClose={()=>setCorrectionDetails(null)} onItem={updateCorrectionItem} onPayment={updateCorrectionPayment} onSave={()=>void saveCorrection()}/>}
 {details&&<div className="catalog-backdrop"><section className="catalog-modal sales-modal sale-details" role="dialog" aria-modal="true"><header><div><span className="eyebrow">Venda</span><h2>Detalhes e auditoria</h2></div><button onClick={()=>setDetails(null)}>×</button></header><div className="sale-detail-summary"><span>Filial <b>{String(details.branch?.name??'—')}</b></span><span>Cliente <b>{String(details.customer?.name??'Consumidor final')}</b></span><span>Total <b>{money(String(details.sale.total_cents??0))}</b></span><span>Status <b>{String(details.sale.status??'—')}</b></span></div><div className="detail-table"><table><thead><tr><th>Produto</th><th>Qtd.</th><th>Unitário</th><th>Desconto</th><th>Total</th></tr></thead><tbody>{details.items.map((item,index)=><tr key={String(item.id??index)}><td>{String(item.productName)}</td><td>{String(item.quantity)}</td><td>{money(String(item.unitSalePriceCents))}</td><td>{money(String(item.discountCents))}</td><td>{money(String(item.totalCents))}</td></tr>)}</tbody></table></div><h3>Pagamentos</h3>{details.payments.map((p,index)=><p key={String(p.id??index)}>{String(p.paymentMethodName)} · <strong>{money(String(p.amountCents))}</strong>{p.externalReference?` · ${String(p.externalReference)}`:''}</p>)}<footer><button className="catalog-primary" onClick={()=>window.print()}>Imprimir</button><button onClick={()=>setDetails(null)}>Fechar</button></footer></section></div>}
 {cancel&&<div className="catalog-backdrop"><section className="catalog-confirm"><span className="material-symbols-rounded">cancel</span><h2>Cancelar venda?</h2><p>O estoque e o movimento de caixa serão estornados. O histórico será preservado.</p><label>Motivo<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Descreva o motivo (mínimo 5 caracteres)"/></label><footer><button onClick={()=>setCancel(null)}>Voltar</button><button className="danger" onClick={()=>void confirmCancel()}>Confirmar cancelamento</button></footer></section></div>}{busy&&<AppLoading text="Atualizando vendas..."/>}</section>
}
